import {
  User,
  Mountain,
  MapPin,
  Package,
  Brush,
  Star,
  Droplets,
  BookOpen,
  Hexagon,
  Monitor,
  Image,
  Grid3x3,
  Box,
  Layers,
  Building,
  PersonStanding,
  Waves,
  Eye,
  Grid2x2,
  Scissors,
  Camera,
  Palette,
  PenTool,
  Sparkles,
  Sailboat,
  Cpu,
  Flame,
  Zap,
  Type,
  Banana,
  Server,
  Shirt,
  Tag,
  Pin,
  FileText,
  Disc,
  DiscAlbum,
  Megaphone,
  Smartphone,
  UserRound,
  Footprints,
  Gem,
  Car,
  Link,
  Laugh,
  Printer,
  Wind,
  Crown,
  ShoppingBag,
  Backpack,
  Baby,
  ChefHat,
  Frame,
  Hand,
  Music,
  CreditCard,
  Stamp,
  Lock,
  Gift,
  Users,
  Armchair,
  Bike,
  Laptop,
  Tablet,
  BicepsFlexed,
  Heart,
  Award,
  BookMarked,
  BookText,
  Headphones,
  GalleryHorizontal,
  GalleryVertical,
  Fingerprint,
  Snowflake,
  Plane,
  Dumbbell,
  Store,
  Phone,
  PaintBucket,
  Paintbrush,
  type LucideProps,
} from "lucide-react";
import {
  TShirt,
  Hoodie,
  Pants,
  Dress,
  Sneaker,
  BaseballCap,
  CoatHanger,
  ShirtFolded,
  Tote,
  Jeep,
  Van,
  Truck,
  CarProfile,
  VinylRecord,
  CassetteTape,
  PersonArmsSpread,
  Bone,
} from "@phosphor-icons/react";
import type { Icon as PhosphorIconType } from "@phosphor-icons/react";
import {
  TankTopIcon,
  LongSleeveIcon,
  ShortsIcon,
  JacketIcon,
  JerseyIcon,
} from "./GarmentIcons";

const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  User,
  Mountain,
  MapPin,
  Package,
  Brush,
  Star,
  Droplets,
  BookOpen,
  Hexagon,
  Monitor,
  Image,
  Grid3x3,
  Box,
  Layers,
  Building,
  PersonStanding,
  Waves,
  Eye,
  Grid2x2,
  Scissors,
  Camera,
  Palette,
  PenTool,
  Sparkles,
  Sailboat,
  Cpu,
  Flame,
  Zap,
  Type,
  Banana,
  Server,
  Shirt,
  Tag,
  Pin,
  FileText,
  Disc,
  DiscAlbum,
  Megaphone,
  Smartphone,
  UserRound,
  Footprints,
  Gem,
  Car,
  Link,
  Laugh,
  Printer,
  Wind,
  Crown,
  ShoppingBag,
  Backpack,
  Baby,
  ChefHat,
  Frame,
  Hand,
  Music,
  CreditCard,
  Stamp,
  Lock,
  Gift,
  Users,
  Armchair,
  Bike,
  Laptop,
  Tablet,
  BicepsFlexed,
  Heart,
  Award,
  BookMarked,
  BookText,
  Headphones,
  GalleryHorizontal,
  GalleryVertical,
  Fingerprint,
  Snowflake,
  Plane,
  Dumbbell,
  Store,
  Phone,
  PaintBucket,
  Paintbrush,
};

// Custom garment SVG icons registered with "garment:" prefix
const GARMENT_MAP: Record<string, React.ComponentType<React.SVGProps<SVGSVGElement>>> = {
  TankTop: TankTopIcon,
  LongSleeve: LongSleeveIcon,
  Shorts: ShortsIcon,
  Jacket: JacketIcon,
  Jersey: JerseyIcon,
};

// Phosphor icons registered with "ph:" prefix
const PHOSPHOR_MAP: Record<string, PhosphorIconType> = {
  TShirt,
  Hoodie,
  Pants,
  Dress,
  Sneaker,
  BaseballCap,
  CoatHanger,
  ShirtFolded,
  Tote,
  Jeep,
  Van,
  Truck,
  CarProfile,
  VinylRecord,
  CassetteTape,
  PersonArmsSpread,
  Bone,
};

interface LucideIconProps extends LucideProps {
  name: string;
}

// Supports Lucide ("Shirt"), Phosphor ("ph:TShirt"), and custom garment ("garment:TankTop") icons.
export function LucideIcon({ name, ...props }: LucideIconProps) {
  if (name.startsWith("garment:")) {
    const garmentName = name.slice(8);
    const GIcon = GARMENT_MAP[garmentName];
    if (!GIcon) return null;
    return <GIcon width="1em" height="1em" {...props} />;
  }
  if (name.startsWith("ph:")) {
    const phosphorName = name.slice(3);
    const PhIcon = PHOSPHOR_MAP[phosphorName];
    if (!PhIcon) return null;
    return <PhIcon weight="regular" {...(props as React.ComponentProps<PhosphorIconType>)} />;
  }
  const Icon = ICON_MAP[name];
  if (!Icon) return null;
  return <Icon {...props} />;
}
